{
    'name': 'it_materiales',
    'version': '1.0',
    'category': 'Administración de Infraestructura y Servicios',
    'description': '"Módulo SIIT para el departamento de materiales del ITSA"',
    'author': 'EDUARDO MORENO MARTINEZ',
    'maintainer': 'I.S.C Javier Cisneros Lucatero ',
    'website': 'http://www.itsa.edu.mx',
    'depends': ['base', 'it_poa', 'it_base'],
    'data': [
        'views/parametros.xml',
        'views/ubicaciones.xml',
        'views/programa.xml',
        'views/compras.xml',
        'views/recepcion.xml',
        'views/listaprecios.xml',
        'views/lista_verificacion.xml',
        'views/catalogoproductos.xml',
        'views/productos.xml',
        'views/entregaproductos.xml',
        'views/evaluacion.xml',
        'views/proveedor.xml',
        'views/criterios.xml',
        'views/departamentos.xml',
        'views/movimientos.xml',
        'views/ordentrabajo.xml',
        'views/solicitud_mantenimiento.xml',
        'views/programa_mantenimiento.xml',
        'views/menu.xml'  
    ],
    'images': ['static/description/icon.png'],
    'installable': True,
    'auto_install': False,
}