{
    'name': 'it_materiales',
    'version': '1.0',
    'category': 'Academica',
    'description': 'Modulo materiales',
    'author': 'EDUARDO MORENO',
    'maintainer': 'Yo',
    'website': 'http://www.itsa.edu.mx',
    'depends': ['base'],
    'data': [
        'views/parametros.xml',
        'views/ubicaciones.xml',
        'views/programa.xml',
        'views/compras.xml',
        'views/recepcion.xml',
        'views/listaprecios.xml',
        'views/catalogoproductos.xml',
        'views/productos.xml',
        #'views/entregaproductos.xml',
        'views/requisiciones.xml',
        'views/evaluacion.xml',
        'views/proveedor.xml',
        'views/criterios.xml',
        'views/menu.xml'  
    ],
    'installable': True,
    'auto_install': False,
}